In [1]:
import pandas as pd

In [5]:
df = pd.read_csv("C:/Users/DELLL/Downloads/ecommerce_customer_behavior.csv")
df

,Customer ID,Age,Gender,Item Purchased,Category,Purchase Amount,Location,Size,Color,Season,Review Rating,Subscription Status,Shipping Type,Discount Applied,Promo Code,Previous Purchases,Payment Mode,Frequency of Purchases
0,1,63,Female,T-Shirt,Clothing,2026,Ahmedabad,M,Maroon,Summer,3.7,Yes,Store Pickup,No,Yes,1,Cash,Weekly
1,2,51,Male,Sneakers,Footwear,4484,Bhopal,M,Pink,Spring,4.2,Yes,Express,No,No,17,UPI,Weekly
2,3,21,Female,Wallet,Accessories,812,Nagpur,L,Navy,Spring,4.2,No,Store Pickup,Yes,No,5,Credit Card,Monthly
3,4,61,Male,Watch,Accessories,395,Ahmedabad,L,Blue,Winter,4.5,No,Free Shipping,No,No,10,Credit Card,Annually
4,5,60,Male,Boots,Footwear,1421,Patna,M,Black,Autumn,2.5,Yes,Free Shipping,Yes,Yes,2,Credit Card,Quarterly
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3995,3996,52,Female,Formal Shoes,Footwear,2676,Kolkata,XL,Grey,Summer,2.2,Yes,Standard,Yes,No,35,Credit Card,Fortnightly
3996,3997,35,Male,Sports Shoes,Footwear,3172,Bangalore,M,Yellow,Summer,2.1,No,Standard,Yes,Yes,19,Cash,Annually
3997,3998,25,Male,Sandals,Footwear,1987,Kolkata,XXL,Pink,Winter,1.1,No,Standard,Yes,Yes,32,Netbanking,Monthly
3998,3999,30,Female,Scarf,Accessories,3801,Nagpur,XL,Maroon,Spring,3.6,Yes,Store Pickup,No,No,8,Cash,Quarterly
3999,4000,54,Female,Loafers,Footwear,70,Kolkata,XL,Grey,Spring,3.3,Yes,Express,Yes,Yes,37,Credit Card,Annually

In [6]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 4000 entries, 0 to 3999
Data columns (total 18 columns):
 #   Column                  Non-Null Count  Dtype
---  ------                  --------------  -----
 0   Customer ID             4000 non-null   int64
 1   Age                     4000 non-null   int64
 2   Gender                  4000 non-null   str
 3   Item Purchased          4000 non-null   str
 4   Category                4000 non-null   str
 5   Purchase Amount         4000 non-null   int64
 6   Location                4000 non-null   str
 7   Size                    4000 non-null   str
 8   Color                   4000 non-null   str
 9   Season                  4000 non-null   str
 10  Review Rating           4000 non-null   float64
 11  Subscription Status     4000 non-null   str
 12  Shipping Type           4000 non-null   str
 13  Discount Applied        4000 non-null   str
 14  Promo Code              4000 non-null   str
 15  Previous Purchases      4000 non-null   int64
 16  Payment Mode            4000 non-null   str
 17  Frequency of Purchases  4000 non-null   str
dtypes: float64(1), int64(4), str(13)
memory usage: 562.6 KB

In [9]:
df.describe(include='all')

,Customer ID,Age,Gender,Item Purchased,Category,Purchase Amount,Location,Size,Color,Season,Review Rating,Subscription Status,Shipping Type,Discount Applied,Promo Code,Previous Purchases,Payment Mode,Frequency of Purchases
count,4000.000000,4000.000000,4000,4000,4000,4000.000000,4000,4000,4000,4000,4000.000000,4000,4000,4000,4000,4000.00000,4000,4000
unique,NaN,NaN,2,33,4,NaN,20,5,12,4,NaN,2,5,2,2,NaN,4,5
top,NaN,NaN,Female,Windcheater,Outwear,NaN,Patna,XL,White,Winter,NaN,No,Express,No,Yes,NaN,Netbanking,Fortnightly
freq,NaN,NaN,2012,156,1025,NaN,221,825,348,1024,NaN,2057,839,2052,2008,NaN,1026,828
mean,2000.500000,42.821250,NaN,NaN,NaN,2500.473750,NaN,NaN,NaN,NaN,2.979625,NaN,NaN,NaN,NaN,24.66150,NaN,NaN
std,1154.844867,15.916081,NaN,NaN,NaN,1461.865538,NaN,NaN,NaN,NaN,1.150114,NaN,NaN,NaN,NaN,14.70493,NaN,NaN
min,1.000000,16.000000,NaN,NaN,NaN,21.000000,NaN,NaN,NaN,NaN,1.000000,NaN,NaN,NaN,NaN,0.00000,NaN,NaN
25%,1000.750000,29.000000,NaN,NaN,NaN,1215.750000,NaN,NaN,NaN,NaN,2.000000,NaN,NaN,NaN,NaN,12.00000,NaN,NaN
50%,2000.500000,42.000000,NaN,NaN,NaN,2509.000000,NaN,NaN,NaN,NaN,3.000000,NaN,NaN,NaN,NaN,24.00000,NaN,NaN
75%,3000.250000,57.000000,NaN,NaN,NaN,3768.250000,NaN,NaN,NaN,NaN,4.000000,NaN,NaN,NaN,NaN,38.00000,NaN,NaN
max,4000.000000,70.000000,NaN,NaN,NaN,5000.000000,NaN,NaN,NaN,NaN,5.000000,NaN,NaN,NaN,NaN,50.00000,NaN,NaN

In [10]:
df.isnull().sum()

Customer ID               0
Age                       0
Gender                    0
Item Purchased            0
Category                  0
Purchase Amount           0
Location                  0
Size                      0
Color                     0
Season                    0
Review Rating             0
Subscription Status       0
Shipping Type             0
Discount Applied          0
Promo Code                0
Previous Purchases        0
Payment Mode              0
Frequency of Purchases    0
dtype: int64

In [12]:
df.columns

Index(['Customer ID', 'Age', 'Gender', 'Item Purchased', 'Category',
       'Purchase Amount', 'Location', 'Size', 'Color', 'Season',
       'Review Rating', 'Subscription Status', 'Shipping Type',
       'Discount Applied', 'Promo Code ', 'Previous Purchases', 'Payment Mode',
       'Frequency of Purchases'],
      dtype='str')

In [13]:
df.columns=df.columns.str.lower()
df.columns=df.columns.str.replace(' ','_')

In [14]:
df.columns

Index(['customer_id', 'age', 'gender', 'item_purchased', 'category',
       'purchase_amount', 'location', 'size', 'color', 'season',
       'review_rating', 'subscription_status', 'shipping_type',
       'discount_applied', 'promo_code_', 'previous_purchases', 'payment_mode',
       'frequency_of_purchases'],
      dtype='str')

In [16]:
df= df.rename(columns={'promo_code_':'promo_code'})
df.columns

Index(['customer_id', 'age', 'gender', 'item_purchased', 'category',
       'purchase_amount', 'location', 'size', 'color', 'season',
       'review_rating', 'subscription_status', 'shipping_type',
       'discount_applied', 'promo_code', 'previous_purchases', 'payment_mode',
       'frequency_of_purchases'],
      dtype='str')

In [18]:
# create a column age_group
labels = ['young_adult', 'adult', 'middle_aged', 'senior']
df['age_group']=pd.qcut(df['age'], q=4, labels=labels)

In [21]:
df[['age','age_group']].head(30)

    age    age_group
0    63       senior
1    51  middle_aged
2    21  young_adult
3    61       senior
4    60       senior
5    29  young_adult
6    48  middle_aged
7    59       senior
8    39        adult
9    62       senior
10   57  middle_aged
11   18  young_adult
12   22  young_adult
13   24  young_adult
14   46  middle_aged
15   29  young_adult
16   20  young_adult
17   24  young_adult
18   34        adult
19   34        adult
20   26  young_adult
21   35        adult
22   27  young_adult
23   17  young_adult
24   22  young_adult
25   58       senior
26   41        adult
27   68       senior
28   31        adult
29   55  middle_aged

In [40]:
#create column purchase frequency days
frequency_mapping = {
    'Fortnightly':14,
    'Weekly':7,
    'Monthly':30,
    'Quarterly':90,
    'Annually':365}

In [41]:
df['purchase_frequency_days']= df['frequency_of_purchases'].map(frequency_mapping)

In [42]:
df[['purchase_frequency_days','frequency_of_purchases']].head(10)

   purchase_frequency_days frequency_of_purchases
0                        7                 Weekly
1                        7                 Weekly
2                       30                Monthly
3                      365               Annually
4                       90              Quarterly
5                      365               Annually
6                       30                Monthly
7                      365               Annually
8                       30                Monthly
9                      365               Annually

In [43]:
df

,customer_id,age,gender,item_purchased,category,purchase_amount,location,size,color,season,review_rating,subscription_status,shipping_type,discount_applied,promo_code,previous_purchases,payment_mode,frequency_of_purchases,age_group,purchase_frequency_days
0,1,63,Female,T-Shirt,Clothing,2026,Ahmedabad,M,Maroon,Summer,3.7,Yes,Store Pickup,No,Yes,1,Cash,Weekly,senior,7
1,2,51,Male,Sneakers,Footwear,4484,Bhopal,M,Pink,Spring,4.2,Yes,Express,No,No,17,UPI,Weekly,middle_aged,7
2,3,21,Female,Wallet,Accessories,812,Nagpur,L,Navy,Spring,4.2,No,Store Pickup,Yes,No,5,Credit Card,Monthly,young_adult,30
3,4,61,Male,Watch,Accessories,395,Ahmedabad,L,Blue,Winter,4.5,No,Free Shipping,No,No,10,Credit Card,Annually,senior,365
4,5,60,Male,Boots,Footwear,1421,Patna,M,Black,Autumn,2.5,Yes,Free Shipping,Yes,Yes,2,Credit Card,Quarterly,senior,90
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3995,3996,52,Female,Formal Shoes,Footwear,2676,Kolkata,XL,Grey,Summer,2.2,Yes,Standard,Yes,No,35,Credit Card,Fortnightly,middle_aged,14
3996,3997,35,Male,Sports Shoes,Footwear,3172,Bangalore,M,Yellow,Summer,2.1,No,Standard,Yes,Yes,19,Cash,Annually,adult,365
3997,3998,25,Male,Sandals,Footwear,1987,Kolkata,XXL,Pink,Winter,1.1,No,Standard,Yes,Yes,32,Netbanking,Monthly,young_adult,30
3998,3999,30,Female,Scarf,Accessories,3801,Nagpur,XL,Maroon,Spring,3.6,Yes,Store Pickup,No,No,8,Cash,Quarterly,adult,90
3999,4000,54,Female,Loafers,Footwear,70,Kolkata,XL,Grey,Spring,3.3,Yes,Express,Yes,Yes,37,Credit Card,Annually,middle_aged,365

In [46]:
df=df.drop('promo_code',axis=1)

In [47]:
df.columns

Index(['customer_id', 'age', 'gender', 'item_purchased', 'category',
       'purchase_amount', 'location', 'size', 'color', 'season',
       'review_rating', 'subscription_status', 'shipping_type',
       'discount_applied', 'previous_purchases', 'payment_mode',
       'frequency_of_purchases', 'age_group', 'purchase_frequency_days'],
      dtype='str')

In [48]:
pip install psycopg2-binary sqlalchemy

Collecting psycopg2-binary
  Downloading psycopg2_binary-2.9.12-cp312-cp312-win_amd64.whl.metadata (5.1 kB)
Collecting sqlalchemy
  Downloading sqlalchemy-2.0.51-cp312-cp312-win_amd64.whl.metadata (9.8 kB)
Collecting greenlet>=1 (from sqlalchemy)
  Downloading greenlet-3.5.3-cp312-cp312-win_amd64.whl.metadata (3.9 kB)
Requirement already satisfied: typing-extensions>=4.6.0 in c:\users\delll\appdata\local\programs\python\python312\lib\site-packages (from sqlalchemy) (4.15.0)
Downloading psycopg2_binary-2.9.12-cp312-cp312-win_amd64.whl (2.8 MB)
   ---------------------------------------- 0.0/2.8 MB ? eta -:--:--
   --- ------------------------------------ 0.3/2.8 MB ? eta -:--:--
   --- ------------------------------------ 0.3/2.8 MB ? eta -:--:--
   ------- -------------------------------- 0.5/2.8 MB 578.7 kB/s eta 0:00:04
   --------------- ------------------------ 1.0/2.8 MB 898.8 kB/s eta 0:00:02
   ------------------- -------------------- 1.3/2.8 MB 1.0 MB/s eta 0:00:02
   ---------------------- ----------------- 1.6/2.8 MB 1.1 MB/s eta 0:00:02
   ---------------------- ----------------- 1.6/2.8 MB 1.1 MB/s eta 0:00:02
   ---------------------- ----------------- 1.6/2.8 MB 1.1 MB/s eta 0:00:02
   ---------------------------------- ----- 2.4/2.8 MB 1.1 MB/s eta 0:00:01
   ---------------------------------------- 2.8/2.8 MB 1.2 MB/s eta 0:00:00
Downloading sqlalchemy-2.0.51-cp312-cp312-win_amd64.whl (2.1 MB)
   ---------------------------------------- 0.0/2.1 MB ? eta -:--:--
   -------------- ------------------------- 0.8/2.1 MB 4.2 MB/s eta 0:00:01
   ----------------------------- ---------- 1.6/2.1 MB 3.8 MB/s eta 0:00:01
   ---------------------------------------- 2.1/2.1 MB 3.4 MB/s eta 0:00:00
Downloading greenlet-3.5.3-cp312-cp312-win_amd64.whl (239 kB)
Installing collected packages: psycopg2-binary, greenlet, sqlalchemy
Successfully installed greenlet-3.5.3 psycopg2-binary-2.9.12 sqlalchemy-2.0.51
Note: you may need to restart the kernel to use updated packages.

[notice] A new release of pip is available: 24.2 -> 26.1.2
[notice] To update, run: C:\Users\DELLL\AppData\Local\Programs\Python\Python312\python.exe -m pip install --upgrade pip

In [49]:
pip install pymysql sqlalchemy

Collecting pymysql
  Downloading pymysql-1.2.0-py3-none-any.whl.metadata (4.3 kB)
Requirement already satisfied: sqlalchemy in c:\users\delll\appdata\local\programs\python\python312\lib\site-packages (2.0.51)
Requirement already satisfied: greenlet>=1 in c:\users\delll\appdata\local\programs\python\python312\lib\site-packages (from sqlalchemy) (3.5.3)
Requirement already satisfied: typing-extensions>=4.6.0 in c:\users\delll\appdata\local\programs\python\python312\lib\site-packages (from sqlalchemy) (4.15.0)
Downloading pymysql-1.2.0-py3-none-any.whl (45 kB)
Installing collected packages: pymysql
Successfully installed pymysql-1.2.0
Note: you may need to restart the kernel to use updated packages.

[notice] A new release of pip is available: 24.2 -> 26.1.2
[notice] To update, run: C:\Users\DELLL\AppData\Local\Programs\Python\Python312\python.exe -m pip install --upgrade pip

In [53]:
import pandas as pd
from sqlalchemy import create_engine
from urllib.parse import quote_plus

# MySQL connection details
username = "root"
password = quote_plus("Prakash@2478")   # Encodes special characters
host = "127.0.0.1"
port = "3306"
database = "first_pr_1"

# Create engine
engine = create_engine(
    f"mysql+pymysql://{username}:{password}@{host}:{port}/{database}"
)

# Write DataFrame to MySQL
table_name = "mytable"
df.to_sql(table_name, con=engine, if_exists="replace", index=False)

# Read data back
result = pd.read_sql("SELECT * FROM mytable LIMIT 5;", con=engine)
print(result)

   customer_id  age  gender item_purchased     category  purchase_amount  \
0            1   63  Female        T-Shirt     Clothing             2026
1            2   51    Male       Sneakers     Footwear             4484
2            3   21  Female         Wallet  Accessories              812
3            4   61    Male          Watch  Accessories              395
4            5   60    Male          Boots     Footwear             1421

    location size   color  season  review_rating subscription_status  \
0  Ahmedabad    M  Maroon  Summer            3.7                 Yes
1     Bhopal    M    Pink  Spring            4.2                 Yes
2     Nagpur    L    Navy  Spring            4.2                  No
3  Ahmedabad    L    Blue  Winter            4.5                  No
4      Patna    M   Black  Autumn            2.5                 Yes

   shipping_type discount_applied  previous_purchases payment_mode  \
0   Store Pickup               No                   1         Cash
1        Express               No                  17          UPI
2   Store Pickup              Yes                   5  Credit Card
3  Free Shipping               No                  10  Credit Card
4  Free Shipping              Yes                   2  Credit Card

  frequency_of_purchases    age_group  purchase_frequency_days
0                 Weekly       senior                        7
1                 Weekly  middle_aged                        7
2                Monthly  young_adult                       30
3               Annually       senior                      365
4              Quarterly       senior                       90

In [54]:
df.head(40)

,customer_id,age,gender,item_purchased,category,purchase_amount,location,size,color,season,review_rating,subscription_status,shipping_type,discount_applied,previous_purchases,payment_mode,frequency_of_purchases,age_group,purchase_frequency_days
0,1,63,Female,T-Shirt,Clothing,2026,Ahmedabad,M,Maroon,Summer,3.7,Yes,Store Pickup,No,1,Cash,Weekly,senior,7
1,2,51,Male,Sneakers,Footwear,4484,Bhopal,M,Pink,Spring,4.2,Yes,Express,No,17,UPI,Weekly,middle_aged,7
2,3,21,Female,Wallet,Accessories,812,Nagpur,L,Navy,Spring,4.2,No,Store Pickup,Yes,5,Credit Card,Monthly,young_adult,30
3,4,61,Male,Watch,Accessories,395,Ahmedabad,L,Blue,Winter,4.5,No,Free Shipping,No,10,Credit Card,Annually,senior,365
4,5,60,Male,Boots,Footwear,1421,Patna,M,Black,Autumn,2.5,Yes,Free Shipping,Yes,2,Credit Card,Quarterly,senior,90
5,6,29,Female,Wallet,Accessories,1761,Kochi,XL,Beige,Autumn,1.6,Yes,Express,No,37,Netbanking,Annually,young_adult,365
6,7,48,Female,Formal Shoes,Footwear,764,Delhi,S,Black,Winter,4.2,No,Store Pickup,Yes,24,Netbanking,Monthly,middle_aged,30
7,8,59,Male,Handbag,Accessories,4418,Jaipur,L,Blue,Spring,2.7,No,Standard,No,32,Cash,Annually,senior,365
8,9,39,Male,Formal Shoes,Footwear,4438,Coimbatore,S,Navy,Spring,3.0,Yes,Free Shipping,No,3,UPI,Monthly,adult,30
9,10,62,Female,Jeans,Clothing,586,Patna,M,Black,Autumn,4.8,Yes,Free Shipping,No,34,UPI,Annually,senior,365
10,11,57,Female,Sweater,Outwear,3608,Coimbatore,XL,Blue,Winter,1.9,No,Standard,Yes,0,Cash,Fortnightly,middle_aged,14
11,12,18,Female,Sandals,Footwear,600,Coimbatore,M,Green,Autumn,1.9,Yes,Store Pickup,No,50,Netbanking,Quarterly,young_adult,90
12,13,22,Female,Sandals,Footwear,2922,Bhopal,XL,Pink,Summer,3.7,Yes,Standard,No,6,UPI,Weekly,young_adult,7
13,14,24,Female,Sports Shoes,Footwear,1523,Jaipur,XL,White,Summer,2.8,Yes,Standard,Yes,48,UPI,Weekly,young_adult,7
14,15,46,Male,Windcheater,Outwear,3305,Delhi,M,Grey,Summer,4.9,No,Next Day,No,44,Netbanking,Weekly,middle_aged,7
15,16,29,Male,Boots,Footwear,4764,Patna,S,Maroon,Spring,1.2,No,Store Pickup,Yes,32,Cash,Weekly,young_adult,7
16,17,20,Male,Ethnic Wear,Clothing,3327,Pune,XXL,White,Summer,3.5,No,Store Pickup,No,13,Credit Card,Weekly,young_adult,7
17,18,24,Female,Cap,Accessories,3765,Surat,S,Red,Autumn,3.5,Yes,Standard,Yes,8,Credit Card,Fortnightly,young_adult,14
18,19,34,Male,Loafers,Footwear,3609,Patna,L,Navy,Summer,3.7,No,Standard,Yes,7,Cash,Monthly,adult,30
19,20,34,Male,Boots,Footwear,2828,Kolkata,L,Brown,Autumn,2.0,Yes,Standard,No,2,Cash,Annually,adult,365
20,21,26,Female,Boots,Footwear,4539,Bhopal,XXL,Red,Summer,1.3,Yes,Store Pickup,Yes,37,UPI,Quarterly,young_adult,90
21,22,35,Female,Sneakers,Footwear,346,Nagpur,M,Beige,Winter,3.7,No,Store Pickup,No,15,UPI,Weekly,adult,7
22,23,27,Female,Hoodie,Outwear,3392,Ahmedabad,L,Black,Summer,2.5,Yes,Next Day,Yes,29,Credit Card,Annually,young_adult,365
23,24,17,Male,Flip Flops,Footwear,3284,Surat,L,Blue,Spring,2.4,No,Store Pickup,No,7,Credit Card,Weekly,young_adult,7
24,25,22,Female,Handbag,Accessories,2851,Surat,XL,Navy,Summer,2.5,Yes,Free Shipping,Yes,0,UPI,Annually,young_adult,365
25,26,58,Female,Hoodie,Outwear,2591,Pune,L,Brown,Spring,3.7,No,Next Day,No,12,Netbanking,Quarterly,senior,90
26,27,41,Male,Boots,Footwear,2509,Lucknow,M,Grey,Spring,2.9,No,Express,No,42,Cash,Annually,adult,365
27,28,68,Male,Wallet,Accessories,2562,Ahmedabad,M,Black,Summer,1.2,No,Store Pickup,Yes,26,UPI,Quarterly,senior,90
28,29,31,Male,Windcheater,Outwear,65,Pune,XL,White,Winter,4.2,No,Standard,Yes,29,UPI,Quarterly,adult,90
29,30,55,Female,Scarf,Accessories,4508,Chandigarh,M,Maroon,Autumn,2.8,Yes,Free Shipping,No,17,Netbanking,Fortnightly,middle_aged,14
30,31,33,Female,Watch,Accessories,2639,Patna,S,Black,Winter,1.9,Yes,Express,Yes,26,Credit Card,Monthly,adult,30
31,32,19,Male,Windcheater,Outwear,3461,Indore,XXL,Maroon,Summer,4.4,No,Next Day,Yes,19,Netbanking,Quarterly,young_adult,90
32,33,30,Female,Sports Shoes,Footwear,3590,Kochi,S,Grey,Spring,3.7,No,Express,No,39,Cash,Quarterly,adult,90
33,34,57,Female,Jeans,Clothing,1131,Chandigarh,M,Red,Spring,2.5,Yes,Next Day,No,48,Netbanking,Annually,middle_aged,365
34,35,69,Male,Blazer,Outwear,3872,Mumbai,XXL,Red,Spring,1.9,Yes,Standard,Yes,12,Cash,Monthly,senior,30
35,36,24,Female,Flip Flops,Footwear,957,Ranchi,M,Pink,Spring,4.1,Yes,Store Pickup,Yes,19,Cash,Monthly,young_adult,30
36,37,52,Female,Shirt,Clothing,3269,Kolkata,S,Navy,Winter,1.4,No,Store Pickup,Yes,22,Netbanking,Annually,middle_aged,365
37,38,57,Female,Skirt,Clothing,123,Bhopal,XL,Blue,Autumn,4.8,No,Express,No,46,Credit Card,Monthly,middle_aged,30
38,39,43,Female,Windcheater,Outwear,2660,Ahmedabad,S,Green,Autumn,2.0,No,Store Pickup,No,1,Netbanking,Annually,middle_aged,365
39,40,29,Female,Sports Shoes,Footwear,2136,Surat,L,Navy,Spring,3.2,Yes,Standard,Yes,31,UPI,Quarterly,young_adult,90